version: 2

project_name: cumulus

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: cml
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/vietdv277/cumulus/cmd.Version={{.Version}}
      - -X github.com/vietdv277/cumulus/cmd.Commit={{.ShortCommit}}
      - -X github.com/vietdv277/cumulus/cmd.BuildDate={{.Date}}

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
